### ISSUE TITLE
パーミッション調査

### ISSUE THREAD

**Issue by kotakawase** [kotakawase/pomoru#124]
Herokuのログをみると以下のエラーが表示されていることが分かった。

```
❯ heroku logs
2022-05-09T02:59:53.880878+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:699:in `dispatch'
2022-05-09T02:59:53.880890+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:727:in `handle_dispatch'
2022-05-09T02:59:53.880901+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:691:in `handle_message'
2022-05-09T02:59:53.880912+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:628:in `websocket_loop'
2022-05-09T02:59:53.880924+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:576:in `connect'
2022-05-09T02:59:53.880935+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:470:in `block in connect_loop'
2022-05-09T02:59:53.880946+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:469:in `loop'
2022-05-09T02:59:53.880958+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:469:in `connect_loop'
2022-05-09T02:59:53.880970+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 02:59:53.880] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:165:in `block in run_async'
2022-05-09T03:00:17.204888+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 03:00:17.204] Gateway message error!
2022-05-09T03:00:17.204927+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 03:00:17.204] Exception: #<Discordrb::Errors::NoPermission: Discordrb::Errors::NoPermission>
2022-05-09T03:00:17.204929+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 03:00:17.204] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/cache.rb:49:in `channel'
2022-05-09T03:00:17.204930+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-09 03:00:17.204] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/events/voice_state_update.rb:27:in `initialize'
```

ここの「Gateway message error!」に着目するとNoPermissionが表示されていて、公式ドキュメントをみるかぎりサーバーへのアクセス許可がちゃんとできないそう。

参考：
- [Module: Discordrb::Errors](http://discordrb.github.io/discordrb/master/Discordrb/Errors.html)
- [Exception: Discordrb::Errors::NoPermission](http://discordrb.github.io/discordrb/master/Discordrb/Errors/NoPermission.html)

---

これを解決すれば正常に動いてくれそう？

**Comment by kotakawase** [comment]
WebSocketを閉じては再開するかのようなエラーでも出てる。

```
2022-05-12T06:27:48.668009+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-12 06:27:48.667] The websocket connection has closed: (no information)
2022-05-12T06:27:48.668029+00:00 app[worker.1]: [INFO : websocket @ 2022-05-12 06:27:48.668] Instant reconnection flag was set - reconnecting right away
2022-05-12T06:27:48.747012+00:00 app[worker.1]: [INFO : websocket @ 2022-05-12 06:27:48.746] Resumed
2022-05-12T07:25:55.598716+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-12 07:25:55.598] The websocket connection has closed: (no information)
2022-05-12T07:25:55.598729+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-12 07:25:55.598] The websocket connection has closed: "Socket EOF in websocket_loop"
2022-05-12T07:25:56.666861+00:00 app[worker.1]: [INFO : websocket @ 2022-05-12 07:25:56.666] Resumed
2022-05-12T08:07:46.222522+00:00 app[worker.1]: [RATELIMIT : ct-7 @ 2022-05-12 08:07:46.222] RL bucket depletion detected! Date: Thu, 12 May 2022 08:07:46 GMT Reset: 1652342866.430
```

**Comment by kotakawase** [comment]
最近は以下のログメッセージが多数表示される。

```
2022-05-15T07:15:42.000012+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:41.999] Gateway message error!
2022-05-15T07:15:42.002428+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] Exception: #<NoMethodError: undefined method `-' for nil:NilClass
2022-05-15T07:15:42.002429+00:00 app[worker.1]: 
2022-05-15T07:15:42.002430+00:00 app[worker.1]: @member_count -= 1
2022-05-15T07:15:42.002431+00:00 app[worker.1]: ^>
2022-05-15T07:15:42.002457+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/data/server.rb:447:in `delete_member'
2022-05-15T07:15:42.002469+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:915:in `delete_guild_member'
2022-05-15T07:15:42.002481+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:1246:in `handle_dispatch'
2022-05-15T07:15:42.002493+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:699:in `dispatch'
2022-05-15T07:15:42.002505+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:727:in `handle_dispatch'
2022-05-15T07:15:42.002517+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:691:in `handle_message'
2022-05-15T07:15:42.002529+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:628:in `websocket_loop'
2022-05-15T07:15:42.002541+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:576:in `connect'
2022-05-15T07:15:42.002552+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:470:in `block in connect_loop'
2022-05-15T07:15:42.002564+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:469:in `loop'
2022-05-15T07:15:42.002576+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:469:in `connect_loop'
2022-05-15T07:15:42.002587+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-15 07:15:42.002] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:165:in `block in run_async'
```

**Comment by kotakawase** [comment]
これも気になる。

```
2022-05-19T06:01:52.959358+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.959] Gateway message error!
2022-05-19T06:01:52.959655+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.959] Exception: #<Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!>
2022-05-19T06:01:52.959774+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.959] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/api.rb:86:in `rescue in raw_request'
2022-05-19T06:01:52.959923+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.959] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/api.rb:80:in `raw_request'
2022-05-19T06:01:52.959999+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.959] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/api.rb:115:in `request'
2022-05-19T06:01:52.960146+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/api/channel.rb:10:in `resolve'
2022-05-19T06:01:52.960182+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/cache.rb:56:in `channel'
2022-05-19T06:01:52.960237+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/events/channels.rb:34:in `initialize'
2022-05-19T06:01:52.960267+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:1218:in `new'
2022-05-19T06:01:52.960320+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:1218:in `handle_dispatch'
2022-05-19T06:01:52.960349+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/bot.rb:699:in `dispatch'
2022-05-19T06:01:52.960399+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:727:in `handle_dispatch'
2022-05-19T06:01:52.960427+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:691:in `handle_message'
2022-05-19T06:01:52.960481+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:628:in `websocket_loop'
2022-05-19T06:01:52.960509+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:576:in `connect'
2022-05-19T06:01:52.960560+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:470:in `block in connect_loop'
2022-05-19T06:01:52.960655+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:469:in `loop'
2022-05-19T06:01:52.960692+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:469:in `connect_loop'
2022-05-19T06:01:52.960728+00:00 app[worker.1]: [ERROR : websocket @ 2022-05-19 06:01:52.960] /usr/local/bundle/gems/discordrb-3.4.0/lib/discordrb/gateway.rb:165:in `block in run_async'
```

> "The bot doesn't have the required permission to do this!"

Botに対して必要な権限がないってことかな？

**Comment by kotakawase** [comment]
ちなみに、開発環境は動いて、本番環境は動かないと勘違いしていたがそうでもなさそう。

![スクリーンショット 2022-05-19 21 16 44](https://user-images.githubusercontent.com/74460623/169291341-4472b445-3a79-4f9e-9438-fe058e3abd31.png)

**Comment by kotakawase** [comment]
最新のdiscordrbを取り込むようにした影響なのか、ここ数日は正常に動作することが確認できているためクローズする。
動作確認やエラーログの監視は引き続き行っておきたい。
